UX: use only one option for settings window
xemu-project/xemu pull request #1122
Opened 2022-06-27 15:10 UTC by revix-0

Fixes: https://github.com/mborgerson/xemu/issues/1059

I've removed the options that were displayed in "general" already since it was redundant to have them both in the menu item list and in another window in general. I renamed "General" into "Settings" so we make it less confused.

2022-06-27 16:26 UTC, antangelo commented
I think it's still handy to have the options immediately available. Perhaps a submenu or something could clarify behavior while maintaining the quick access options?

2022-06-27 16:37 UTC, abaire commented
> I think it's still handy to have the options immediately available. Perhaps a submenu or something could clarify behavior while maintaining the quick access options?

@antangelo can you expand on your suggestion? Maybe I'm misunderstanding, but given that launching into the general page provides the full list of subpages on the left it seems to me that it's roughly equivalent to a submenu (except in the case where you actually want general settings, in which case it saves a step).

2022-06-27 17:57 UTC, antangelo commented
I whipped this up quickly to demonstrate, shouldn't be hard to isolate it:
![image](https://user-images.githubusercontent.com/25046221/176005052-34535ae6-0f07-4ab6-996d-fc04b201f923.png)

It's not a huge deal to click into the settings menu and then use the sidebar to navigate, but I think doing it this way is slightly faster to navigate (saves a click).

I think at minimum, if opening the settings menu is to be done with a single button, it should open the previously opened tab (as opposed to opening the General tab, which is the behavior in this PR from the looks of things).

2022-06-27 18:56 UTC, revix-0 commented
the changes i made make sure that we keep track of the last visited window when exiting and entering back into "Settings", tho if we access Help > About instead of Settings > About, and then we access to Settings, the last value is saved to that window. Let me know if this is not a big issue with the UI design.

2023-06-06 15:47 UTC, antangelo commented
This branch needs to be synced with upstream to resolve conflicts

2023-08-03 13:27 UTC, Fabxx commented
Code has been rebased on the lastes xemu version

2023-08-04 20:05 UTC, antangelo commented on ui/xui/menubar.cc
> -            if (ImGui::MenuItem("About")) g_main_menu.ShowAbout();
Why is this removed?

2023-08-04 20:05 UTC, antangelo commented on ui/xui/popup-menu.cc
> -        if (PopupMenuButton("Snapshots...", ICON_FA_CLOCK_ROTATE_LEFT)) {
Why is this removed?

2023-08-04 20:05 UTC, antangelo commented on ui/xui/welcome.cc
> -        g_main_menu.ShowSystem();
Why is this changed? We should take users directly to the system settings for initial setup

2023-10-16 00:50 UTC, mborgerson commented
Thanks for the patch. Since it has been confusing for some users, we can make Settings one single option in the menu. Can you simplify the patch and remove unrelated changes

2023-10-16 00:51 UTC, mborgerson requested changes
Thanks for the patch. Since it has been confusing for some users, we can make Settings one single option in the menu. Can you simplify the patch and remove unrelated changes

2023-11-06 10:22 UTC, Fabxx commented on ui/xui/popup-menu.cc
> -        if (PopupMenuButton("Snapshots...", ICON_FA_CLOCK_ROTATE_LEFT)) {
All these ifs were related to the items in the drop-down menu. But since now the structure has been simplified into one item "Settings", and it keeps track of the last viewed window these ifs are not necessary anymore.

2023-11-06 10:23 UTC, Fabxx commented on ui/xui/welcome.cc
> -        g_main_menu.ShowSystem();
My bad, will restore the function to ShowSystem on first boot

2023-11-06 22:38 UTC, antangelo commented on ui/xui/popup-menu.cc
> -        if (PopupMenuButton("Snapshots...", ICON_FA_CLOCK_ROTATE_LEFT)) {
This is the popup menu entry, not the menubar entry.

2023-11-07 08:05 UTC, Fabxx commented on ui/xui/popup-menu.cc
> -        if (PopupMenuButton("Snapshots...", ICON_FA_CLOCK_ROTATE_LEFT)) {
> This is the popup menu entry, not the menubar entry.

I see, but what is their exact behavior? because even by removing them the internal menu works when clicking on items. Can you do a video to showcase these specific elements? Maybe i'm missing something

2023-11-07 10:31 UTC, Fabxx commented on ui/xui/menubar.cc
> -            if (ImGui::MenuItem("About")) g_main_menu.ShowAbout();
Restored in last commit

2023-11-07 10:33 UTC, Fabxx commented
> Thanks for the patch. Since it has been confusing for some users, we can make Settings one single option in the menu. Can you simplify the patch and remove unrelated changes

I aborted the modifications that did not regard the actual drop down menu (got confused with the popup menu naming convention). Now we only have the simplified drop-down menu.

2023-11-09 04:28 UTC, antangelo commented
Do you think we should persist the last opened menu tab after xemu restart? This information is already stored in the `last_viewed_menu_index` config item.

2023-11-09 09:05 UTC, Fabxx commented
> Do you think we should persist the last opened menu tab after xemu restart? This information is already stored in the `last_viewed_menu_index` config item.

i could reset the index to 0 after the first setup, so if a reboot happens the user will be prompted to the first tab of the settings section

2023-11-10 02:27 UTC, antangelo commented
I don't think that's quite the same idea that I had. If you were on the snapshots tab, for example, and you close xemu, I think that when you re-open xemu and open settings from the menubar, you should be shown the snapshots tab again.
Do you think this behavior is better than the current behavior (which resets to the general tab)?

2023-11-10 09:41 UTC, Fabxx commented
> I don't think that's quite the same idea that I had. If you were on the snapshots tab, for example, and you close xemu, I think that when you re-open xemu and open settings from the menubar, you should be shown the snapshots tab again. Do you think this behavior is better than the current behavior (which resets to the general tab)?



> I don't think that's quite the same idea that I had. If you were on the snapshots tab, for example, and you close xemu, I think that when you re-open xemu and open settings from the menubar, you should be shown the snapshots tab again. Do you think this behavior is better than the current behavior (which resets to the general tab)?

The current behavior is this: if the user doesn't move from the settings tab and just restarts it is prompted to the General tab. But if the user moves, on next boot it will be prompted to the last selected window, because the `m_current_view_index = 0` gets overrided by the other functions when you change tabs. So i do continue to keep track of the last visited window, but only if the user didn't move from settings on first boot. on next boots this thing won't happen and will just keep track of the last visited window

2023-11-10 22:30 UTC, antangelo commented
It keeps track of the visited window within a session, but in my testing if I close xemu and re-open it, the general tab is always shown (regardless of what I had open before).

2023-11-10 22:35 UTC, Fabxx commented
> It keeps track of the visited window within a session, but in my testing if I close xemu and re-open it, the general tab is always shown (regardless of what I had open before).

are you writing the index assignation into `ShowSettings` or `ShowSystem`?

2023-11-10 22:41 UTC, antangelo commented
I have not modified the code, I just checked out the branch as-is

2023-11-10 22:45 UTC, Fabxx commented
> I have not modified the code, I just checked out the branch as-is

oh, well as i said the modification is not here yet. I have to write it now

2023-11-10 23:03 UTC, antangelo commented
I have no idea what that change is supposed to do, or what issue you're trying to address. Whatever you're trying to fix seems to be completely independent from the suggestion I made. `m_current_view_index` does not retain or restore any value between xemu sessions.

2023-11-11 10:38 UTC, Fabxx commented
> I have no idea what that change is supposed to do, or what issue you're trying to address. Whatever you're trying to fix seems to be completely independent from the suggestion I made. `m_current_view_index` does not retain or restore any value between xemu sessions.

i'm not understanding what's the problem that you're experiencing. I thought the trouble was that after the welcome setup was that the user was always redirected to the general tab when opening settings again, so i made it that if the user moves in the tabs after the first setup on next boot it would find himself on the last viewed tab, if he doesn't move he's redirected to general tab. But then again if this is not the issue show me what would you like to do, visually or in code

2023-11-11 20:09 UTC, antangelo commented
1. Open xemu, navigate to Machine -> Settings
2. Select a tab that is not General (e.g. Audio)
3. Close the settings window and then close xemu.
4. Open xemu again, and navigate to Machine -> Settings
5. Observe that the General tab is open, and not the previously selected tab (in the example above, Audio)

I haven't noticed any issues with the welcome flow both with and without your latest change, the system button should always show the system page in that case.

2023-11-11 20:27 UTC, Fabxx commented
understood, will try to fix it

2023-11-12 11:30 UTC, Fabxx commented
OK so the idea i had is to write the last viewed window index into xemu.toml, and then read it when the user boots xemu and initialize the index again to the last visited window. I need some help in understanding how to write to the toml file

2023-11-12 18:26 UTC, antangelo commented
The last viewed tab is already stored in the config for you as `last_viewed_menu_index`

2023-11-12 19:03 UTC, Fabxx commented
> The last viewed tab is already stored in the config for you as `last_viewed_menu_index`

yeah i found it, is it ok if the function becomes like this?
```
void MainMenuScene::ShowSettings()
{
    m_current_view_index = g_config.general.last_viewed_menu_index;
    SetNextViewIndexWithFocus(m_current_view_index);
}
```

2023-11-14 23:09 UTC, antangelo commented
You don't need to assign `m_current_view_index`, it will be updated later. You should be able to just use the config entry as the argument to `SetNextViewIndexWithFocus`.

2023-11-15 17:07 UTC, Fabxx commented
> You don't need to assign `m_current_view_index`, it will be updated later. You should be able to just use the config entry as the argument to `SetNextViewIndexWithFocus`.

done it, thanks for the suggestion, let me know if there is anything else to do

2023-11-16 03:11 UTC, antangelo commented
Is this PR now ready for review or is it still in development?

2023-11-19 19:16 UTC, merged