Device emulation
xemu-project/xemu pull request #1478
Opened 2023-07-15 00:35 UTC by faha223

Added functionality to emulate an Xbox Controller S or a Steel Battalion controller in addition to the existing emulated Xbox controller

2023-12-31 09:15 UTC, Florin9doi commented on hw/xbox/xid-steel-battalion.c
> +    uint8_t     CockpitHatch_EmergencyEject;
```suggestion
    uint8_t     EmergencyEject : 4;
    uint8_t     CockpitHatch : 4;
    uint8_t     Ignition : 4;
    uint8_t     Start : 4;
    ....
```

2023-12-31 09:20 UTC, Florin9doi commented on hw/xbox/xid-steel-battalion.c
> +    print_steel_battalion_leds("Cockpit Hatch", "Emergency Eject", state->CockpitHatch_EmergencyEject);
```suggestion
    fprintf(stderr, "%s: %d\n", "Emergency Eject", state->EmergencyEject);
    fprintf(stderr, "%s: %d\n", "Cockpit Hatch", state->CockpitHatch);
    fprintf(stderr, "%s: %d\n", "Ignition", state->Ignition);
    fprintf(stderr, "%s: %d\n", "Start", state->Start);
    ....
```

2024-01-03 14:16 UTC, faha223 commented on hw/xbox/xid-steel-battalion.c
> +    print_steel_battalion_leds("Cockpit Hatch", "Emergency Eject", state->CockpitHatch_EmergencyEject);
I've never seen this syntax before, but it looks like it could be really useful. Thanks!

2024-01-03 14:16 UTC, faha223 commented on hw/xbox/xid-steel-battalion.c
> +    uint8_t     CockpitHatch_EmergencyEject;
I've never seen this syntax before, but it looks like it could be really useful. Thanks!

2024-03-09 22:26 UTC, carlosgamer23 commented
The emulator could make it easier by having its own frontend, something close to PCSX2, so we can organize the games and put our own covers on them.  Have you also thought about creating a compression format for the isos?  Something like Dolphin did with RVZ, so that it is supported by Xemu (maybe a compression format called .xe ? Haha 😅)

2024-05-11 20:18 UTC, faha223 commented
I'm thinking I should maybe add light gun to this

2024-06-11 14:03 UTC, Florin9doi commented on ui/xui/main-menu.cc
> +        for (int i = 0; i < 5; i++) {
```suggestion
        for (int i = 0; i < ARRAY_SIZE(driver_display_names); i++) {
```

2024-06-11 14:03 UTC, Florin9doi commented on ui/xui/main-menu.cc
> +        const char *driver_display_names[5] = {
```suggestion
        const char *driver_display_names[] = {
```

2024-06-11 14:03 UTC, Florin9doi commented on ui/xui/main-menu.cc
> +        const char *available_drivers[5] = { DRIVER_DUKE, DRIVER_S,
```suggestion
        const char *available_drivers[] = { DRIVER_DUKE, DRIVER_S,
```

2024-06-11 15:56 UTC, faha223 commented on ui/xui/main-menu.cc
> +        for (int i = 0; i < 5; i++) {
I like this suggestion, but implementing it as-is causes the build to fail because the ARRAY_SIZE macro uses the struct keyword after all is resolved. 

I'm going to play around with this and see if I can come up with a good solution

2025-01-27 04:07 UTC, MasonT8198 commented
This looks great!

2025-01-27 04:10 UTC, MasonT8198 requested changes

2025-01-27 04:10 UTC, MasonT8198 commented on ui/xui/input-manager.cc
> +        controller_focus_capture); // FIXME: Rename 'test mode'
Nit: why adjust the spacing

2025-01-27 04:10 UTC, MasonT8198 commented on ui/xui/input-manager.cc
> +    int16_t axis[CONTROLLER_AXIS__COUNT] = { 0 };
nit: spacing

2025-01-27 04:10 UTC, MasonT8198 commented on ui/xemu-input.h
> +int xemu_input_get_controller_default_bind_port(ControllerState *state,
nit: spacing

2025-01-27 04:10 UTC, MasonT8198 commented on ui/xemu-input.h
> +    // (FIXME)
Nit: Spacing

2025-01-27 04:10 UTC, MasonT8198 commented on ui/xui/input-manager.cc
> +    // alive
Nit: Spacing

2025-01-27 04:11 UTC, MasonT8198 commented
There are also some merge conflicts to be resolved however they don't seem super major, just a note

2025-01-27 12:34 UTC, faha223 commented
I'm closing this PR as it has been replaced by 4 smaller PRs that, when combined, accomplish the same thing

2025-01-27 12:34 UTC, closed without merging