UI: Add games directory and allow switching of games via controller in popup-menu
xemu-project/xemu pull request #1627
Opened 2024-03-30 16:11 UTC by TrentSeed

At the moment, switching between games in Xemu typically requires using a mouse/keyboard. When using a game controller, it's possible to open the popup menu, and select "Load Disc...", however that launches a native file browser which does not have controller input support, requiring use of a mouse/keyboard to select the target file. The goal of this PR is to make switching between games a bit more convenient and possible using a controller.

This PR introduces a new setting called "Games directory" within Settings > General > Miscellaneous. By default there is no value specified, and when clicked the user is presented with a file browser to select the desired directory containing .iso game files.

When the popup menu is activated (via right click, or start/back from an Xbox Controller S), there is now a "Games" submenu button that when selected, will present the user with a sorted list of games based on the configured directory. Selecting a game will result in Xemu loading the corresponding disc file. In the event no .iso files are detected in the directory, or if the directory is still undefined, there is an option "No games found" that when selected will open the main settings UI so that the user may adjust the games directory as needed.

![All Settings](https://github.com/xemu-project/xemu/assets/6829425/9108708e-5bfc-480c-a809-49c22128a0ad)

![Root Popup Menu](https://github.com/xemu-project/xemu/assets/6829425/e0c47a09-f7ac-43c7-988d-e8fdd160c788)

![Games Popup Menu - With .iso Files Found](https://github.com/xemu-project/xemu/assets/6829425/07b540f4-91e6-46dc-962f-deec71ab51d1)

![Games Popup Menu - No Files Found / Directory Not Set](https://github.com/xemu-project/xemu/assets/6829425/f6bea035-d683-45e9-9881-c8ccff123577)

2024-04-11 13:24 UTC, schulle334 approved these changes

2024-05-06 23:11 UTC, mborgerson requested changes

2024-05-06 23:11 UTC, mborgerson commented on ui/xui/popup-menu.cc
> +            if (PopupMenuButton(label, ICON_FA_GAMEPAD)) {
Should probably use the disc icon instead of a gamepad

2024-05-06 23:11 UTC, mborgerson commented on ui/xui/popup-menu.cc
> +        if (std::filesystem::is_directory(directory)) {
We should avoid querying the filesystem in the draw loop

2024-05-06 23:11 UTC, mborgerson commented on ui/xui/popup-menu.cc
> +#include "popup-menu.hh"
Please revert any unnecessary header order changes

2024-05-10 03:05 UTC, TrentSeed commented on ui/xui/popup-menu.cc
> +            if (PopupMenuButton(label, ICON_FA_GAMEPAD)) {
Sounds good, icon has been updated to ICON_FA_COMPACT_DISC

2024-05-10 03:06 UTC, TrentSeed commented on ui/xui/popup-menu.cc
> +        if (std::filesystem::is_directory(directory)) {
File system is no longer queried in the draw loop

2024-05-10 03:06 UTC, TrentSeed commented on ui/xui/popup-menu.cc
> +#include "popup-menu.hh"
Done

2024-05-23 02:05 UTC, mborgerson commented
Thanks for addressing the review feedback. I've rebased onto the latest version of the `master` branch. Can you please fix the build issues, then I'll happily merge.

2025-10-16 00:32 UTC, mborgerson commented
Sorry it's taken a while to come back to this. I'll close in favor of #2449 for rebase and minor improvements, but your authorship will be retained! Thanks for the improvement.

2025-10-16 00:32 UTC, closed without merging