Update User Interface & Add Additional Options To IR Scaling, UI Scaling, & Aspect Ratio settings
xemu-project/xemu pull request #1628
Opened 2024-04-01 16:39 UTC by Joshua-1248

Adds additional options for Increase Internal Resolution, UI Scale, & Aspect Ratio settings in the main-menu.cc file.

Some minor changes have been made to the descriptions.

2024-04-04 17:16 UTC, MasonT8198 requested changes
Reviewed…

Also, when submitting PRs we follow a general commit name structure

So in this case you edited main-menu.cc so the commit would be

`main-menu.cc: Clarify menu descriptions` or something along those lines.

I do agree that some of these descriptions could use a little touching up though.

2024-04-04 17:16 UTC, MasonT8198 commented on ui/xui/main-menu.cc
> +    Toggle("Check For Updates", &g_config.general.updates.check,
Nit: “Check for Updates” would be the grammatically correct notation

2024-04-04 17:16 UTC, MasonT8198 commented on ui/xui/main-menu.cc
> +           "Checks for updates whenever xemu is opened");
Nit: “Check for updates whenever xemu is opened” is also the correct notation, why was this changed?

2024-04-04 17:16 UTC, MasonT8198 commented on ui/xui/main-menu.cc
> +    Toggle("Cache Shaders To Disk", &g_config.perf.cache_shaders,
Nit: “Cache Shaders to Disk” otherwise this is fine

2024-04-04 17:16 UTC, MasonT8198 commented on ui/xui/main-menu.cc
> +    Toggle("Fast Boot", &g_config.general.skip_boot_anim,
Nit: “Skip Startup Animation” makes more sense than “Fast Boot”, in the context of what the config option, although I see what you’re getting across, however if these were going to be changed, do note that the `&g_config` lines should be changed to mimic the change in name scheme

2024-04-04 17:16 UTC, MasonT8198 commented on ui/xui/main-menu.cc
>                       "Select preferred startup window size")) {
Nit: This is **a lot** of config options, making the scrollbar look somewhat cluttered, maybe it’d be worth considering to use a selection of general options, and adding a custom toggle where you can type in what resolution that you would like to use?

Furthermore, some of these config options make no real sense? As they would make most games look unplayable

2024-04-04 17:16 UTC, MasonT8198 commented on ui/xui/main-menu.cc
> +    Toggle("VSync", &g_config.display.window.vsync,
Nit: I believe that the general notation of vsync is `V-Sync` however I’m amenible to the difference

2024-04-04 17:16 UTC, MasonT8198 commented on ui/xui/main-menu.cc
> -                          "This button will overwrite the existing snapshot.",
Nit: The plain description for this does work pretty well, I wouldn’t change it

2024-04-04 17:16 UTC, MasonT8198 commented on ui/xui/main-menu.cc
> +    Toggle("Fullscreen On Startup",
Nit: “Fullscreen on Startup”

2024-04-04 17:16 UTC, MasonT8198 commented on ui/xui/main-menu.cc
> +    if (Toggle("Fullscreen", &fs, "Enable Fullscreen")) {
I like this change, makes more sense

2024-04-04 17:16 UTC, MasonT8198 commented on ui/xui/main-menu.cc
> +                msg = "Select Create to create new snapshot";
Nit: select and press do the same thing, also the msg doubling of `create to create` adds some redundant language to the message

Perhaps something along the lines of `Select Create to Generate New Snapshot`

Also this change doesn’t follow your prior commit theme of capitalizing statements.

2024-04-05 10:09 UTC, Joshua-1248 commented on ui/xui/main-menu.cc
> +    Toggle("Check For Updates", &g_config.general.updates.check,
Gotcha. Changed it to lower-case.

2024-04-05 10:11 UTC, Joshua-1248 commented on ui/xui/main-menu.cc
> +           "Checks for updates whenever xemu is opened");
Was not sure which to choose. Will leave it as "Check" instead of "Checks"

2024-04-05 10:13 UTC, Joshua-1248 commented on ui/xui/main-menu.cc
> +    Toggle("Cache Shaders To Disk", &g_config.perf.cache_shaders,
Done

2024-04-05 10:17 UTC, Joshua-1248 commented on ui/xui/main-menu.cc
> +    Toggle("Fast Boot", &g_config.general.skip_boot_anim,
Gotcha.

Restored default descriptor to "Skip Startup Animation"

2024-04-05 10:34 UTC, Joshua-1248 commented on ui/xui/main-menu.cc
>                       "Select preferred startup window size")) {
A custom resolution config option would definitely work better in that regard, both for reducing clutter & for allowing the user to set the resolution to anything that fits their needs.

2024-04-05 12:36 UTC, Joshua-1248 commented on ui/xui/main-menu.cc
> +    Toggle("VSync", &g_config.display.window.vsync,
Changed to V-Sync

2024-04-05 12:37 UTC, Joshua-1248 commented on ui/xui/main-menu.cc
> -                          "This button will overwrite the existing snapshot.",
Reverted description to original one

2024-04-05 12:38 UTC, Joshua-1248 commented on ui/xui/main-menu.cc
> +    Toggle("Fullscreen On Startup",
Done

2024-04-05 12:38 UTC, Joshua-1248 commented on ui/xui/main-menu.cc
> +                msg = "Select Create to create new snapshot";
Done

2024-04-05 17:26 UTC, mborgerson commented
I appreciate the PR, but I disagree with these changes and will be closing the PR. The capitalization of menu option text is intentional and I don't wish for it to change, the plethora of added options don't seem necessary to me and will not work correctly as written, and the other misc. changes really seem like typos.

2024-04-05 17:26 UTC, closed without merging