Window starts smaller
xemu-project/xemu pull request #258
Opened 2021-03-14 07:40 UTC by MasonT8198

This change is because without it there is an issue where the menu settings disappear because of a smaller screens

2021-03-14 08:51 UTC, GXTX commented
Are people using 800x600 these days? Looking at Steams hardware survey (although a bit biased towards "gamers") 1024x768 is 0.2% of the population, `statcounter.com` puts the same at 1% globally.

2021-03-14 09:00 UTC, MasonT8198 commented
> Are people using 800x600 these days? Looking at Steams hardware survey (although a bit biased towards "gamers") 1024x768 is 0.2% of the population, `statcounter.com` puts the same at 1% globally.

It's the way it starts, on some laptop screens and some tv screens it'll start without the hud, and you have to fiddle around with it to make the hud reappear.

2021-03-17 03:31 UTC, medievil1 commented
experience this myself.. 1920x1080 here but my dpi on a 50" display is 150%
dunno it is related as well... without setting it to use application size in the override(win 10/file properties) it will start top and bottom touching the full 1080 res and with the top cut off.....
click the side to resize and boom, snaps into correct range

2021-03-17 03:33 UTC, MasonT8198 commented
> experience this myself.. 1920x1080 here but my dpi on a 50" display is 150%
> 
> dunno it is related as well... without setting it to use application size in the override(win 10/file properties) it will start top and bottom touching the full 1080 res and with the top cut off.....
> 
> click the side to resize and boom, snaps into correct range

It has to do with the way windows app scaling is. I have it happen on my 4k tv as well, it gets super big so it breaks xemu. Because scaling issues.

2021-03-17 04:04 UTC, mborgerson commented
The preferred fix is to query maximum window size (size of screen) and create a window no larger than current screen

2021-03-20 10:22 UTC, MasonT8198 commented
> The preferred fix is to query maximum window size (size of screen) and create a window no larger than current screen

how would you go about doing this

2021-05-18 20:39 UTC, mborgerson commented
See https://wiki.libsdl.org/SDL_GetCurrentDisplayMode

2021-05-18 22:47 UTC, mborgerson requested changes
Please check host resolution first as suggested

2021-05-19 19:03 UTC, mborgerson commented on ui/xemu.c
> +    // Query Window Size and Print The Display Mode
You have queried the screen size, now we need to make sure that we don't create a window larger than that size.

2021-05-20 04:54 UTC, MasonT8198 commented on ui/xemu.c
> +    // Query Window Size and Print The Display Mode
Yes, my trouble is trying to find the command to limit those bounds, in SDL there is a command to adjust the screen size to those bounds but not limit them

2021-05-25 03:26 UTC, mborgerson commented on ui/xemu.c
> +    // Query Window Size and Print The Display Mode
You can limit them when we create the window where we specify window dimensions

2021-12-28 22:19 UTC, mborgerson commented
This is unfinished. I'll close for now and we can return with a follow up PR.

2021-12-28 22:19 UTC, closed without merging