Fix XEMU branding in windows
xemu-project/xemu pull request #262
Opened 2021-03-19 02:56 UTC by MasonT8198

2021-03-19 03:27 UTC, MasonT8198 commented
This should fix issue #222

2021-03-19 08:57 UTC, mzji commented on version.rc
>        VALUE "LegalTrademarks", "QEMU is a trademark of Fabrice Bellard."
Maybe this `QEMU` can also be replaced?

2021-03-19 09:31 UTC, mzji commented on version.rc
> +      VALUE "FileVersion", XEMU_VERSION
`QEMU_VERSION` is actually a predefined macro, thus it cannot be replaced so simply...

2021-03-19 09:34 UTC, MasonT8198 commented on version.rc
> +      VALUE "FileVersion", XEMU_VERSION
Sorry about that, changed the wrong one 🥲

2021-03-19 21:31 UTC, dracc commented on version.rc
> +      VALUE "LegalTrademarks", "XEMU is a trademark of Matt Borgerson."
Is this actually true?
Also I'm not sure it's a good idea to alter the qemu copyright stuff.

2021-03-19 22:05 UTC, MasonT8198 commented on version.rc
> +      VALUE "LegalTrademarks", "XEMU is a trademark of Matt Borgerson."
Sorry about that

2021-03-24 00:05 UTC, mborgerson requested changes

2021-03-24 00:05 UTC, mborgerson commented on version.rc
> +      VALUE "FileDescription", "XEMU Xbox Emulator"
xemu: Original Xbox Emulator

2021-03-24 00:05 UTC, mborgerson commented on version.rc
> +      VALUE "LegalCopyright", "Copyright Various Authors. Released under the GNU General Public License."
Capitalization change not necessary

2021-03-24 00:05 UTC, mborgerson commented on version.rc
>        VALUE "FileVersion", QEMU_VERSION
Make sure this actually has the xemu version in it

2021-03-24 00:05 UTC, mborgerson commented on version.rc
> +      VALUE "ProductName", "XEMU"
Lowercase `xemu` is what I've been using

2021-05-18 22:02 UTC, merged