Add Better UI Support for 4K TVs
xemu-project/xemu pull request #271
Opened 2021-03-26 02:47 UTC by MasonT8198

Hey Matt, I decided to open this in a Separate PR because if it got shot down I'd rather this one closed instead of removing it from the other PR. But Basically, in Windows/Linux on a 4k TV even at 300% scaling on the display. But basically this is for the ease of use for people with a HTPC and want to play it on their TV, I know I do often, but I could see it at UI Scaling 2x, But I know that people with Glasses or people without couldn't because I have really good vision.

2021-03-26 03:13 UTC, MasonT8198 commented
Second Add-In, sorry for the PR spam

2021-03-26 05:25 UTC, dracc commented
> Second Add-In, sorry for the PR spam

Do not worry about that, PRs touching five different things *are* worse.

Re changes: nit: bad commit titles (try prepending `ui: ` and modifying the rest of them to fit).

2021-05-18 22:04 UTC, Vaporeon commented
Perhaps it would be better to not have a hard-coded size menu for this but instead draw at a consistent scale that increases with resolution much like game UI's do.

2021-05-18 22:11 UTC, MasonT8198 commented
> Perhaps it would be better to not have a hard-coded size menu for this but instead draw at a consistent scale that increases with resolution much like game UI's do.

I could see this being a feature implemented in the feature, I just appended the changes onto the already existing system, as when I use a bigger sized TV, 2x doesn't really help much, granted for me I can see it, but my dad couldn't or my stepmom, so I figured the feature would be a nice addition to an already existing system

2021-05-18 22:41 UTC, mborgerson requested changes
There is also a check in `xemu_hud_init` that would need to be updated

2021-05-18 22:41 UTC, mborgerson commented on ui/xemu-hud.cc
> +            if (ui_scale_combo > 1) ui_scale_combo = ui_scale_combo;
This statement now has no effect

2021-05-18 22:41 UTC, mborgerson commented on ui/xemu-hud.cc
> -
Please restore blank line

In general when submitting patches please try to follow the existing style

2021-05-18 22:41 UTC, mborgerson commented on ui/xemu-hud.cc
> +            ImGui::SameLine(); HelpMarker("Controls how the UI is scaled, not Surface Scaling");
I'm not sure this is necessary

2021-05-18 22:44 UTC, mborgerson commented
> Perhaps it would be better to not have a hard-coded size menu for this but instead draw at a consistent scale that increases with resolution much like game UI's do.

I welcome a more intuitive/automatic scaling method. Can you prototype this?

2021-05-19 19:07 UTC, mborgerson commented on ui/xemu-hud.cc
> +
Please avoid whitespace changes like this a 2 more below.

2021-05-19 19:07 UTC, mborgerson commented on ui/xemu-hud.cc
> +            if (ImGui::Combo("UI Scale", &ui_scale_combo, "1x\0" "2x\0" "3x\0" "4x\0")) {
Don't forget to fix bounds checking when we initialize g_ui_scale at startup

2021-08-25 13:06 UTC, MasonT8198 commented
@mborgerson got around to fixing up this one, it's been a while, so something may have been done incorrectly.

2021-10-03 16:35 UTC, MasonT8198 commented
@mborgerson

2022-03-01 15:10 UTC, MasonT8198 commented
This one has gone stale, I think it's clean now however I am closing this

2022-03-01 15:10 UTC, closed without merging