pgraph.c: Clear Surfaces and Shader Cache
xemu-project/xemu pull request #447
Opened 2021-08-27 04:53 UTC by MasonT8198

This should finish the pgraph_destroy function and clear out the surface and shader cache properly when pgraph_destroy is called.

2021-08-27 05:52 UTC, GXTX commented on hw/xbox/nv2a/pgraph.c
> +sudo apt update/*
?

2021-08-27 05:55 UTC, MasonT8198 commented on hw/xbox/nv2a/pgraph.c
> +sudo apt update/*
Hmm, I pasted in two places at the same time apparently. 2 am programming tends to extend horrible results

2021-09-08 14:15 UTC, MasonT8198 commented
There may be a pointer that is being used incorrectly but it should be correct.

2021-09-15 08:45 UTC, mborgerson commented on hw/xbox/nv2a/pgraph.c
> +    lru_flush(&pg->shader_cache);
shader_cache is not LRU type

2021-09-15 08:45 UTC, mborgerson commented on hw/xbox/nv2a/pgraph.c
> +    lru_flush(&pg->surfaces);
surfaces is not lru type

2021-09-15 08:46 UTC, mborgerson requested changes
See mentioned

2021-09-24 03:19 UTC, MasonT8198 commented on hw/xbox/nv2a/pgraph.c
> +    lru_flush(&pg->shader_cache);
Excuse my ineptitude but what type is shader_cache

2021-09-24 03:19 UTC, MasonT8198 commented on hw/xbox/nv2a/pgraph.c
> +    lru_flush(&pg->surfaces);
What type is surfaces

Googling didn't seem to get me anywhere meaningful

2021-09-24 20:27 UTC, GXTX commented on hw/xbox/nv2a/pgraph.c
> +    lru_flush(&pg->shader_cache);
What type is `pg`? And you'll find your answer.

2021-12-28 22:14 UTC, mborgerson commented
Let's return to this with a follow-up PR

2021-12-28 22:14 UTC, closed without merging