nv2a: Set frequency to 233MHz
xemu-project/xemu pull request #474
Opened 2021-10-06 00:37 UTC by GXTX

No clue about the coefficients and such but the frequency is supposed to be 233MHz according to `XBOverclock`. This might not even matter if it gets set in `pramdac_write` correctly.

Unrelated has anyone seen if nxdk apps work recently? I get a black screen, or a broken Xbox logo, and if I reset I can see what was supposed to be shown as if the surface wasn't updated.

2021-10-11 18:28 UTC, MasonT8198 commented
> Unrelated has anyone seen if nxdk apps work recently? I get a black screen, or a broken Xbox logo, and if I reset I can see what was supposed to be shown as if the surface wasn't updated.

I haven't had this issue no, I've also asked a few other people, what bios and mcpx combo are you using?

2021-12-28 23:34 UTC, mborgerson commented on hw/xbox/nv2a/nv2a.c
> +    d->pramdac.core_clock_freq = 233000000;
According to the expression in `pramdac_write` a `core_clock_coeff` of `0x11c01` actually gives 233333324. Let's update this value to be consistent

2021-12-28 23:35 UTC, mborgerson requested changes
See inline

2021-12-29 00:25 UTC, GXTX commented on hw/xbox/nv2a/nv2a.c
> +    d->pramdac.core_clock_freq = 233000000;
Fixed

2021-12-29 00:40 UTC, mborgerson commented
Thanks!

2021-12-29 00:40 UTC, merged

2022-02-24 09:55 UTC, GXTX commented
Coming back to this... I've been playing around with "overclocking" xemu, I don't think we should actually be setting these in reset, and if we do we should probably just zero the values. The x-codes should be what's setting this.