nv2a: Software decompression for compressed 3D textures
xemu-project/xemu pull request #48
Opened 2020-10-30 01:37 UTC by wilkovatch

This should resolve #40

2020-10-30 03:34 UTC, mborgerson requested changes

2020-10-30 03:34 UTC, mborgerson commented on hw/xbox/nv2a/pgraph.c
> +static inline void decode_bc1_colors(uint16_t c0,
Can we move these decompression functions into a new file, e.g. s3tc.{c|h}

2020-10-30 03:34 UTC, mborgerson commented on hw/xbox/nv2a/pgraph.c
> +    if (color_format == GL_COMPRESSED_RGBA_S3TC_DXT1_EXT) {
Can we refactor this a bit into separate respective functions for each block decompression algorithm? We can then handle the block swizzling separately (and only once) from the block decompression logic, and reduce the amount of nested loops/repeated code here.

2020-10-30 18:51 UTC, wilkovatch commented
Is it better now? Anyway, this is what I was talking about yesterday on Discord about code duplication/deduplication (in the end I was just being paranoid about the possible performance overhead, since in fact after refactoring all I added to the main loop are just a couple of ifs)

2020-10-30 19:20 UTC, dracc commented
Why closed? :(

2020-10-30 19:23 UTC, wilkovatch commented
I did something stupid and the build fails on macOS, I'll create a new pull request when I sort this out

2020-10-30 20:11 UTC, PatrickvL commented
Perhaps change the decoder interface to allow reuse of an externally allocated buffer, to reduce strain on memory allocater?

2020-10-30 20:31 UTC, mborgerson commented
@wilkovatch 
> Is it better now? Anyway, this is what I meant yesterday on Discord when I was talking about code duplication/deduplication (in the end I was just being paranoid about the possible performance overhead

Much better! Thank you for the changes. I will try to review it as soon as possible.

> I did something stupid and the build fails on macOS, I'll create a new pull request when I sort this out

No need to create a new pull request. You can rebase+force-push to your original branch it will update the PR accordingly.

@PatrickvL
> Perhaps change the decoder interface to allow reuse of an externally allocated buffer, to reduce strain on memory allocater?

If necessary the code can be changed to allocate a scratch buffer upon startup, but I'd prefer to keep it simple like this for now.

2020-10-30 21:19 UTC, wilkovatch commented
Ok, I'll try to update this one...

2020-10-31 23:27 UTC, mborgerson commented on hw/xbox/nv2a/s3tc.h
> +
Please include conventional C pre-processor header guards, e.g.:

```c
#ifndef S3TC_H
#define S3TC_H

...

#endif
```

2020-10-31 23:27 UTC, mborgerson commented on hw/xbox/nv2a/s3tc.c
> +    uint8_t a0 = *block;
nit: Could be written `block[0]` and `block[1]` respectively

2020-10-31 23:27 UTC, mborgerson commented on hw/xbox/nv2a/s3tc.c
> +    for(int a_i = 0; a_i < 16; a_i++){
nit: Space following `for` keyword

2020-10-31 23:27 UTC, mborgerson commented on hw/xbox/nv2a/s3tc.c
> +                                     uint8_t* r,
nit: In general the code base follows a convention of having the `*` character next to the variable name, e.g. `uint8_t *r`. In this case however, as we know the dimensions of the array, let's go with `uint8_t r[4]` etc. Cases repeated below for other functions.

2020-10-31 23:27 UTC, mborgerson commented on hw/xbox/nv2a/s3tc.c
> +    r[0] = ((c0 & 0xF800) >> 8) * 0xFF / 0xF8,
Looks great here, I like how you broke this color decoder out.

2020-10-31 23:27 UTC, mborgerson commented on hw/xbox/nv2a/s3tc.c
> +{
To be safe, can we include some checks on the input here to safeguard against crazy situations like we saw previously; e.g.

```c
assert((width > 0) && (width % 4 == 0));
assert((height > 0) && (height % 4 == 0));
assert(depth > 0);
...
```

In case of Xbox, these dimensions must also be power-of-two, but we don't need such a restriction here if your decoder can handle NPOT all the same.

2020-10-31 23:28 UTC, mborgerson commented
Hi @wilkovatch, I'm not quite finished reviewing yet (still need to look over the block swizzling) but I've left some initial feedback for you. So far things are looking great with only minor fixes requested. Thanks for making updates so far!

2020-10-31 23:36 UTC, mborgerson commented on hw/xbox/nv2a/s3tc.c
> +static inline void decompress_dxt1_block(const uint8_t* data,
Let's simplify this function by pre-calculating the `data` pointer and remove the `block_index`, `block_depth`, and `slice` arguments here.

2020-10-31 23:50 UTC, mborgerson commented on hw/xbox/nv2a/s3tc.c
> +                    for (int y = y0; y < y1; y++) {
Would you refactor this segment into a separate function which is then called from the corresponding decompress_dxtX_block s.t. when we decompress a block it actually populates a pixel array instead of just producing the indices.

2020-11-01 02:42 UTC, wilkovatch commented
@mborgerson Fixes done, let me know if I forgot anything.

2020-11-02 00:48 UTC, mborgerson commented
Thank you @wilkovatch! There is some minor refactoring I'd like to see done, but this is ready to merge now and we can iterate on it in the future.

I've tested your code with [some simple scripts here](https://github.com/mborgerson/test-xemu-s3tc-volume-compress), and I've tested my compressor against hardware so everything appears to check out. I've also made sure this works with the compressed 3D texture Conker uses in its main menu and it looks to work just fine.

Thanks for the work!

2020-11-02 00:50 UTC, mborgerson approved these changes

2020-11-02 00:53 UTC, closed without merging

2020-11-02 00:56 UTC, mborgerson commented
It looks like I force-pushed upstream master to your branch and accidentially wiped out your commit in the process of rebasing. Sorry about that. However, your work is safe and has been integrated into xemu's master branch.