Improve Unicode filename handling on Windows
xemu-project/xemu pull request #499
Opened 2021-10-17 16:04 UTC by CookiePLMonster

All identified UTF-8/Unicode issues have been fixed, now xemu can:
* Run from a directory with Unicode characters
* Load/save settings to a directory with Unicode characters (typically non-ASCII user names)
* Load BIOS/hard disc from directories with Unicode characters
* Run games from directories with Unicode characters

![image](https://user-images.githubusercontent.com/7947461/137635367-989b279b-7241-4053-8ef4-ea63f66a9474.png)
Here it's been tested with nonsense paths, but in practice this means that if those paths work, then e.g. paths with Russian, Japanese or Chinese characters will also work fine.

There may be more places that need fixing, but basing on my testing of the above, all known broken cases are now handled properly.

Fixes #479

2021-10-17 18:03 UTC, PatrickvL requested changes
A few suggestions

2021-10-17 18:03 UTC, PatrickvL commented on hw/core/loader.c
> +        error_setg_errno(errp, errno, "Failed to open_utf8 file: %s", filename);
Perhaps this replacement of `open` by `open_utf8` is not necessary?

2021-10-17 18:03 UTC, PatrickvL commented on hw/core/loader.c
> +        fprintf(stderr, "Could not open_utf8 option rom '%s': %s\n",
Perhaps this replacement of `open` by `open_utf8` is not necessary?

2021-10-17 18:11 UTC, CookiePLMonster commented on hw/core/loader.c
> +        fprintf(stderr, "Could not open_utf8 option rom '%s': %s\n",
Good catch on this and on the above, a Find & Replace fail.

2021-10-17 23:01 UTC, GXTX commented
I have no real review for this. It seems there are issues with base QEMU that are also being fixed. Can this be upstreamed?

2021-10-18 08:43 UTC, CookiePLMonster commented
> Can this be upstreamed?

Technically it probably can, but from what I know qemu's barrier of entry for contributions is rather steep and I'm not sure I want to deal with the entire ritual right now.

2021-10-18 08:46 UTC, simi commented
@CookiePLMonster if you can prepare separate patch against QEMU only, I can try to help contribute this to QEMU directly.

2021-10-18 08:48 UTC, CookiePLMonster commented
> @CookiePLMonster if you can prepare separate patch against QEMU only, I can try to help contribute this to QEMU directly.

Sounds good! Let's wait until this is reviewed though to avoid going back with possible additional fixes.

2021-10-19 00:48 UTC, mborgerson commented on block/file-win32.c
> +    wchar_t* wfilename;
nit: `*` goes next to name

2021-10-19 00:48 UTC, mborgerson commented on block/file-win32.c
> +    wchar_t* wfilename;
nit: `*` goes next to identifier

2021-10-19 00:48 UTC, mborgerson commented on block/file-win32.c
>                            FILE_SHARE_READ, NULL,
nit: Indentation

2021-10-19 00:48 UTC, mborgerson commented on ui/noc_file_dialog.h
> +        wfilters = (wchar_t*)g_convert(filters, filters_length + 1, "UTF-16", "UTF-8", NULL, NULL, NULL);
* Why the use of `g_convert` here, and `g_utf8_to_utf16` elsewhere?
* Can you confirm this handles all string terminating `\x00` correctly for number of strings > 1
* If conversion fails, `wfilters` and other converted strings will be `NULL` and no filters will be displayed. I think in this case an error should be generated.

2021-10-19 00:48 UTC, mborgerson commented on ui/noc_file_dialog.h
> +    {
nit: braces goes on line with `if`, `else` keywords

2021-10-19 00:48 UTC, mborgerson commented on util/oslib-win32.c
> +    wchar_t* wfilename;
nit: `*` goes next to identifier

2021-10-19 00:48 UTC, mborgerson commented on util/oslib-win32.c
> +        error_setg(errp, "Failed to create PID file");
Error message should be different, or these should be grouped below like other error handlers

2021-10-19 00:48 UTC, mborgerson commented on util/oslib-win32.c
> +    if (!wfilename)
nit: Braces should be on line with `if`, `else`

2021-10-19 00:48 UTC, mborgerson commented on util/oslib-win32.c
> +    wchar_t *wfilename = NULL;
Initialization of variable unnecessary

2021-10-19 00:48 UTC, mborgerson commented on util/oslib-win32.c
> +    wchar_t *wfilename = NULL;
Initialization of variable unnecessary

2021-10-19 00:48 UTC, mborgerson commented on util/oslib-win32.c
> +    {
nit: Braces

2021-10-19 00:48 UTC, mborgerson commented on util/oslib-win32.c
> +}
nit: Newline here

2021-10-19 00:48 UTC, mborgerson commented on util/oslib-win32.c
> +    if (!wpathname)
nit: Braces

2021-10-19 00:48 UTC, mborgerson commented on hw/core/loader.c
> +    fd = open_utf8(filename, O_RDONLY | O_BINARY);
Hmm.. Preferably all `open`, `fopen`, `access`, etc. would be replaced with `qemu_*` prefix versions and the encoding conversion would be handled there.

This is okay for now, but something I'd like to see refactored. I really want to avoid having the code base mixing `X` and `X_utf8` variants in different spots, and using the prefixed version would make it easier to detect usages of these encoding issue-prone versions.

If you are planning to send a patch to upstream QEMU, I suggest doing this.

2021-10-19 00:48 UTC, mborgerson commented on ui/noc_file_dialog.h
> +    OPENFILENAMEW ofn;       // common dialog box structure
nit: comment alignment

2021-10-19 00:48 UTC, mborgerson commented on ui/noc_file_dialog.h
> +        _wmakepath_s(szFile, _MAX_PATH, NULL, NULL, fname, ext);
Why have some buffer sizes been replaced with `G_N_ELEMENTS(buffer)` element count wrappers and others remain to be their original definition constant value (e.g. `_MAX_PATH`)?

2021-10-19 00:48 UTC, mborgerson commented on ui/noc_file_dialog.h
> +        g_noc_file_dialog_ret = strdup(gszFile);
Why duplicate and free the converted string? We should already have an allocation to keep (`free` above will need to be `g_free`)

2021-10-19 00:48 UTC, mborgerson commented on util/oslib-win32.c
> +    char* ret;
nit: `*` goes next to identifier

2021-10-19 00:48 UTC, mborgerson commented on util/oslib-posix.c
> +int open_utf8(const char *filename, int oflag)
Prefer these passthru functions to be in header

2021-10-19 00:48 UTC, mborgerson commented on util/oslib-win32.c
> +                             /* SHGFP_TYPE_CURRENT */ 0, wbase_path);
nit: param alignment

2021-10-19 00:48 UTC, mborgerson commented on util/oslib-win32.c
> +    base_path = g_utf16_to_utf8(wbase_path, -1, NULL, NULL, NULL);
What if conversion fails?

2021-10-19 00:48 UTC, mborgerson commented on ui/noc_file_dialog.h
> +    wchar_t* wfilters = NULL;
nit: `*` placements

2021-10-19 00:48 UTC, mborgerson commented on util/oslib-win32.c
>          p--;
Comparison with path terminator `'\\'` should probably have `L` prefix

2021-10-19 00:48 UTC, mborgerson commented on util/oslib-win32.c
> +    len = GetModuleFileNameW(NULL, buf, G_N_ELEMENTS(buf) - 1);
Apparently it is possible to have a path longer than `MAX_PATH`, in which case the module path may be truncated. This consideration also complicates below `MAX_PATH` cases--although, we can leave it for follow up as its an existing issue.

2021-10-19 00:48 UTC, mborgerson commented on util/oslib-win32.c
> +    wchar_t *wpathname = NULL;
Initialization unnecessary

2021-10-19 00:48 UTC, mborgerson commented on ui/xemu-settings.c
> +#include "qemu/osdep.h"
osdep.h should come first in includes

2021-10-19 00:48 UTC, mborgerson commented on ui/noc_file_dialog.h
> +#include <stdio.h>
Why is stdio.h added?

2021-10-19 19:21 UTC, CookiePLMonster commented on ui/noc_file_dialog.h
> +        wfilters = (wchar_t*)g_convert(filters, filters_length + 1, "UTF-16", "UTF-8", NULL, NULL, NULL);
`g_convert` handles embedded nulls, `g_utf8_to_utf16` does not (even when you specify length explicitly).

2021-10-19 19:22 UTC, CookiePLMonster commented on hw/core/loader.c
> +    fd = open_utf8(filename, O_RDONLY | O_BINARY);
The reason I decided against it is because `qemu_open` already means something else and it doesn't even return a fd or `FILE*`. If you have other ideas for a function name, I'll happily rename those.

2021-10-19 19:22 UTC, CookiePLMonster commented on ui/noc_file_dialog.h
> +        _wmakepath_s(szFile, _MAX_PATH, NULL, NULL, fname, ext);
Looks like an oversight.

2021-10-19 19:23 UTC, CookiePLMonster commented on ui/noc_file_dialog.h
> +        g_noc_file_dialog_ret = strdup(gszFile);
If the above is the only place where `g_noc_file_dialog_ret` is freed, then I can simplify this. I just didn't want to mix the allocators.

2021-10-19 19:23 UTC, CookiePLMonster commented on util/oslib-posix.c
> +int open_utf8(const char *filename, int oflag)
Is there a posix specific oslib header?

2021-10-19 19:24 UTC, CookiePLMonster commented on ui/noc_file_dialog.h
> +#include <stdio.h>
Leftover from an earlier test, will remove.

2021-10-19 20:07 UTC, CookiePLMonster commented on util/oslib-win32.c
> +    wchar_t *wfilename = NULL;
In this case, I'd like to keep it for consistency with `wmode` that must be initialized.

2021-10-19 20:15 UTC, CookiePLMonster commented on util/oslib-win32.c
> +    len = GetModuleFileNameW(NULL, buf, G_N_ELEMENTS(buf) - 1);
It's generally very annoying to account for that in `GetModuleFileName`, since the usual "call the first time to get the buffer size, then again to fill the buffer" idiom of WinAPI does not apply to this function.

2021-10-21 19:44 UTC, mborgerson commented on hw/core/loader.c
> +    fd = open_utf8(filename, O_RDONLY | O_BINARY);
> The reason I decided against it is because `qemu_open` already means something else and it doesn't even return a fd or `FILE*`.

`qemu_open` is a thin wrapper around `open`, and returns a file descriptor. See util/osdep.c

2021-10-21 19:47 UTC, mborgerson commented on ui/noc_file_dialog.h
> +    else {
nit: `else {` goes on line with preceding bracket

2021-10-21 19:48 UTC, mborgerson commented on ui/noc_file_dialog.h
> +        wfilters = (wchar_t*)g_convert(filters, filters_length + 1, "UTF-16", "UTF-8", NULL, NULL, NULL);
> `g_convert` handles embedded nulls, `g_utf8_to_utf16` does not (even when you specify length explicitly).

Interesting; thanks for clarifying.

Did you consider my other feedback regarding possible failed conversion?

2021-10-21 19:49 UTC, mborgerson commented on util/oslib-posix.c
> +int open_utf8(const char *filename, int oflag)
You can use the header that you've defined them in already, with a macro for Windows platform detection.

2021-10-21 19:50 UTC, CookiePLMonster commented on ui/noc_file_dialog.h
> +        wfilters = (wchar_t*)g_convert(filters, filters_length + 1, "UTF-16", "UTF-8", NULL, NULL, NULL);
I'm not sure how to gracefully display an error in this context? If you have an example of that, I'll amend.

2021-10-21 19:50 UTC, CookiePLMonster commented on hw/core/loader.c
> +    fd = open_utf8(filename, O_RDONLY | O_BINARY);
You're right, I must've missed it. Do you think in this case I should modify `qemu_open` to handle UTF-8 gracefully and also add `qemu_fopen` that calls `qemu_open` + `fdopen` internally?

2021-10-21 19:51 UTC, mborgerson commented on util/oslib-win32.c
> +    len = GetModuleFileNameW(NULL, buf, G_N_ELEMENTS(buf) - 1);
In this case the approach could be to call `GetModuleFileName` with a reasonable buffer size, then double the buffer size and retry every time it throws a truncation error. Anyway, it's a problem to be solved later.

2021-10-21 19:53 UTC, mborgerson commented on util/oslib-win32.c
> +    {
nit: Brace should be moved up

2021-10-21 19:54 UTC, mborgerson commented on util/oslib-win32.c
> +    wchar_t *wfilename = NULL;
I think it is clear in the code, as the assignment happens 3 lines later. Not a huge deal, just redundant

2021-10-21 19:58 UTC, mborgerson commented on hw/core/loader.c
> +    fd = open_utf8(filename, O_RDONLY | O_BINARY);
That would be fine

2021-10-21 20:02 UTC, mborgerson commented on ui/noc_file_dialog.h
> +        wfilters = (wchar_t*)g_convert(filters, filters_length + 1, "UTF-16", "UTF-8", NULL, NULL, NULL);
How about we simply print a message to `stderr` then return NULL

2021-10-21 20:13 UTC, mborgerson commented on util/oslib-win32.c
> +        /* this shouldn't happen, so something is very wrong if it does */
Comment isn't necessary (aborting is unusual)

2021-10-21 21:34 UTC, CookiePLMonster commented on util/oslib-win32.c
> +    len = GetModuleFileNameW(NULL, buf, G_N_ELEMENTS(buf) - 1);
I agree, let's solve it in a separate PR.

2021-10-22 21:56 UTC, mborgerson commented on include/qemu/osdep.h
> +static FILE *qemu_fopen(const char *filename, const char *mode)
Let's add the `inline` keyword here to silence compiler complaining about unused static functions. Same with below function.

2021-10-22 22:05 UTC, mborgerson requested changes

2021-10-22 22:05 UTC, mborgerson commented on util/osdep.c
> +#ifdef O_CLOEXEC
We can simplify this function by moving the path,mode encoding into a thin open wrapper function (just static define it above this function), then we can keep original `qemu_open_cloexec` logic as it was before, but replace its `open` call with your new encoding handle version of `open`.

2021-10-24 19:09 UTC, merged

2021-10-24 19:12 UTC, mborgerson commented
Thank you for this contribution!

I have amended your original commit message to more closely align with repo conventions and make more explicit the changes of the patch.