xbox: Change PCI IDs for USB and IDE controllers to match Xbox
xemu-project/xemu pull request #591
Opened 2021-12-06 03:30 UTC by GXTX

I don't have my Xbox-Linux drive image (nor a working Xbox) any longer so I can't 100% confirm but going by my past tests should be enough.

Checking out my original patch (#130) on IDs, Matt had suggested getting a proper dump of the config space of all of the devices, someone should do that *for completeness*.

2021-12-06 14:11 UTC, binarymaster commented on hw/usb/hcd-ohci-pci.c
>      dc->desc = "Apple USB Controller";
```suggestion
#ifdef XBOX
    dc->desc = "nForce USB Controller";
#else
    dc->desc = "Apple USB Controller";
#endif
```

2021-12-06 19:43 UTC, GXTX commented on hw/usb/hcd-ohci-pci.c
>      dc->desc = "Apple USB Controller";
Is this presented to the OS? If so is that the correct description?

2021-12-06 23:21 UTC, binarymaster commented on hw/usb/hcd-ohci-pci.c
>      dc->desc = "Apple USB Controller";
Not sure, it might be some internal QEMU thing. Just suggested it for the consistence.

2021-12-25 01:35 UTC, GXTX commented on hw/usb/hcd-ohci-pci.c
>      dc->desc = "Apple USB Controller";
I dumped the USB reg area and didn't see any plain text like this. I assume this isn't passed onto the OS.

2021-12-28 23:58 UTC, mborgerson commented on hw/usb/hcd-ohci-pci.c
>      dc->desc = "Apple USB Controller";
It is used in device infrastructure (e.g. when printing out available devices). I agree with @binarymaster's suggested patch; Let's update the device description string while we are updating the id for consistency.

2021-12-28 23:58 UTC, mborgerson requested changes
See inline

2021-12-29 00:25 UTC, GXTX commented on hw/usb/hcd-ohci-pci.c
>      dc->desc = "Apple USB Controller";
Fixed

2021-12-29 00:42 UTC, merged