nv2a: cache shaders to disk
xemu-project/xemu pull request #768
Opened 2022-03-14 08:41 UTC by antangelo

Shaders now use an LRU cache eviction strategy. On shader compilation, the shader programs will be saved to disk. On shutdown, a list of shaders currently in the LRU cache is saved to disk as well. On startup, this list (along with all shaders in it) are then loaded, effectively restoring the shader cache to the state it was when the emulator was last closed.

I have tested this on Linux, Windows, and macOS. Unfortunately, my Intel MacBook Pro doesn't support saving and loading program binaries, so I have only been able to verify that case on macOS.

2022-03-19 16:56 UTC, abaire commented on hw/xbox/nv2a/pgraph.c
> +    fwrite(&node->hash, sizeof(uint64_t), 1, lru_list_file);
Check to see if the write was successful

2022-03-19 16:56 UTC, abaire commented on hw/xbox/nv2a/pgraph.c
> +    FILE *lru_list = qemu_fopen(shader_lru_path, "wb");
Should we write to a temp file first and then move only once the write is completed?

My worry is that a power outage or untimely hard kill could leave a partially written cache file. Doing a move would minimize the failure window.

2022-03-19 16:56 UTC, abaire commented on hw/xbox/nv2a/pgraph.c
> +    const size_t shader_cache_size = 50*1024;
Out of curiosity, how did you decide on 50k?

2022-03-19 16:56 UTC, abaire commented on hw/xbox/nv2a/pgraph.c
> +void pgraph_cache_shaders_to_disk(NV2AState *d)
Double checking as I'm not super familiar with the qemu life cycle: is it possible to get into a state where the `shader_disk_thread` is still running and the LRU cache is still being mutated when this is called?

If that's guaranteed by the life cycle, maybe we should add a comment or assert to clarify that this should only be called during the shutdown state?

If not, should we lock the cache while it's being populated and here while it's being saved?

2022-03-19 16:56 UTC, abaire commented on hw/xbox/nv2a/pgraph.c
> +    fseek(lru_shaders_list, 0, SEEK_END);
Nit: While I think it's probably fine on all of the platforms xemu supports, I believe `SEEK_END` behavior is not actually guaranteed by the standard.

2022-03-19 16:56 UTC, abaire commented on hw/xbox/nv2a/pgraph.c
> +    for (size_t read = 0; read < shader_list_size; read += sizeof(uint64_t)) {
Should we bomb out early if `shader_list_size` is not evenly divisible by `sizeof(uint64_t)` (presumably that'd indicate that the cache is corrupted or truncated)?

2022-03-19 16:56 UTC, abaire commented on hw/xbox/nv2a/pgraph.c
> +    if (glGetError() != GL_NO_ERROR) {
This seems potentially trace-worthy (w/ the actual error preserved).

2022-03-19 16:56 UTC, abaire commented on hw/xbox/nv2a/shaders.c
> +        assert(false);
Can we use `assert(!"Some meaningful message")` so that user reports are less prone to expire? 

Trying to look at year+ old "It crashes with assert(false); at line <something_long_since_moved_around>" makes it more painful to try to address problems than it needs to be.

2022-03-19 16:56 UTC, abaire commented on hw/xbox/nv2a/shaders.c
> +GLenum get_gl_primitive_mode(enum ShaderPolygonMode polygon_mode, enum ShaderPrimitiveMode primitive_mode)
Is this refactoring intentionally part of this PR?

2022-03-19 16:56 UTC, abaire commented on hw/xbox/nv2a/shaders.c
> +    /* Create an option geometry shader and find primitive type */
Supernit: Since you're in here, I believe the intent was to say "optional" not "option"

2022-03-19 16:56 UTC, abaire commented on ui/xemu-settings.c
> +	char *base = xemu_settings_detect_portable_mode()
Why not take the same approach as `xemu_settings_get_path` and permacache this so the caller doesn't have to remember to free it?

2022-03-19 16:56 UTC, abaire commented on ui/xemu-settings.c
> +	char *path = g_malloc(strlen(base) + 1);
`g_strdup`?

2022-03-19 16:56 UTC, abaire commented on ui/xemu-settings.c
>  const char *xemu_settings_get_path(void)
GH won't let me comment below, but should we update `xemu_settings_get_path` to use `xemu_get_config_dir_path` to reduce code duplication? I assume these should never drift.

2022-03-19 16:56 UTC, abaire commented on hw/xbox/nv2a/pgraph.c
> +    /* program_size might be zero on some systems, if no binary formats are supported */
Should we differentiate between these two cases then? If `program_size` is 0, bail out silently. If it's not zero but `g_malloc` failed, blow up (or at least yell in the log)?

2022-03-19 16:56 UTC, abaire commented on hw/xbox/nv2a/pgraph.c
> +static void shader_cache_to_disk(ShaderLruNode *snode)
(I don't know enough about GL shader binding performance) Is the performance of this new cache writing comparable to the old trivial hash table insertion?

2022-03-19 16:56 UTC, abaire commented on hw/xbox/nv2a/pgraph.c
> +    snprintf(name, 20, "%llu", (unsigned long long) snode->node.hash);
Nit: maybe "scache-%llu" or something so it's clear what threads with 20 character hashes are really for (and in case we find a need to cache other things using background threads in the future)

2022-03-19 16:56 UTC, abaire commented on hw/xbox/nv2a/pgraph.c
> +    if (!shader_file) {
Should we warn on any of these failures?

If a user complained about performance issues and it turned out that the shader cache was never being updated for some reason I think it'd be useful to know when trying to diagnose the problem.

2022-03-19 16:56 UTC, abaire commented on hw/xbox/nv2a/pgraph.c
> +cleanup:
Nit, maybe "error_cleanup" or "fail_cleanup" or something that indicates that this is only meant to be jumped to in a failure case?

2022-03-19 16:56 UTC, abaire commented on hw/xbox/nv2a/pgraph.c
> +    written = fwrite(snode->program, snode->program_size, 1, shader_file);
I'd suggest we write the program size explicitly as well. With the current code I think the size of the program is inferred by subtracting sizeof GLEnum + SS from the total size, which means a file that is truncated for some reason (e.g., xemu crashing during this write) would be treated as a valid entry. If we write the size explicitly and we can verify that the total cache file size matches expectations as a proxy for validating that the program data is correct.

2022-03-19 16:56 UTC, abaire commented on hw/xbox/nv2a/pgraph.c
> +static void shader_load_from_disk(PGRAPHState *pg, uint64_t hash)
Nit: Maybe `shader_cache_load_from_disk` or `shader_cache_read_from_disk` to be aligned with naming used below (`shader_cache_write_to_disk` specifically). Or vice versa, rename below to be aligned with this.

2022-03-19 16:56 UTC, abaire commented on hw/xbox/nv2a/pgraph.c
> +    snprintf(shader_path, shader_path_len, "%s/shaders/%llu", cfg_dir, (unsigned long long) hash);
Maybe make the format string a constant or create a helper function to get the shader cache path for a hash, since it's important that the read here and the write function below to use the same path?

2022-03-19 16:56 UTC, abaire commented on hw/xbox/nv2a/pgraph.c
> +    size_t shader_size = ftell(shader_file) - sizeof(GLenum) - sizeof(ShaderState);
I added a comment in the write path below, but I'm worried that this would happily accept truncated files (as long as they're at least 1 byte larger than the enum + state sizes).

2022-03-19 16:56 UTC, abaire commented on hw/xbox/nv2a/pgraph.c
> +    snode->program = program_buffer;
If you corrupt the program data in the cache file, what happens when it's used out of the cache? Do we have a path to regen? If not, should we also add a hash or CRC of the program so we can be confident that we're not adding a vector for HDD corruption to introduce inexplicable crashes?

2022-03-19 18:08 UTC, PatrickvL commented on hw/xbox/nv2a/shaders.c
> +GLenum get_gl_primitive_mode(enum ShaderPolygonMode polygon_mode, enum ShaderPrimitiveMode primitive_mode)
Besides below, it's also called from shader_load_from_memory(), so it seems intentional

2022-03-19 18:19 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +void pgraph_cache_shaders_to_disk(NV2AState *d)
Good catch, I can call `qemu_thread_join` on it before visiting the LRU entries.

2022-03-19 18:19 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +    FILE *lru_list = qemu_fopen(shader_lru_path, "wb");
It's not critical that the LRU list is written properly: the load routine will fail quietly if it cannot load part or all of the list, and then regenerate those shaders that it was unable to load when they are next encountered.

I suppose this would result in losing part of the cache and having to regenerate it, which isn't ideal.

2022-03-19 18:19 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +    const size_t shader_cache_size = 50*1024;
Copied it from the element cache, mostly. I tested a game that compiled shaders every time the camera was moved, so I don't think this value is unreasonable (it might be low, even).

2022-03-19 18:19 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +    if (glGetError() != GL_NO_ERROR) {
Take a look at the spec: https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glProgramBinary.xhtml
It only fails if `gl_program` is invalid, or if the program binary format is unsupported (which can happen due to driver updates). I didn't think it was necessary to log these, as they result in the shader being regenerated anyway.

2022-03-19 18:19 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +static void shader_load_from_disk(PGRAPHState *pg, uint64_t hash)
Good point, will fix.

2022-03-19 18:19 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +    snprintf(shader_path, shader_path_len, "%s/shaders/%llu", cfg_dir, (unsigned long long) hash);
Will fix.

2022-03-19 18:19 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +    snode->program = program_buffer;
I had assumed that `glProgramBinary` will validate that the binary is valid but this doesn't seem to be the case. I'll fix this by using `glValidateProgram` after loading.

2022-03-19 18:19 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +    fseek(lru_shaders_list, 0, SEEK_END);
I don't know if there's another good cross-platform way to do this. I can move it into the platform specific utils in case we introduce a new platform that doesn't support it, but I don't know if that's necessary at this point.

2022-03-19 18:19 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +    for (size_t read = 0; read < shader_list_size; read += sizeof(uint64_t)) {
I don't think it makes a difference, if it's not a multiple of `sizeof(uint64_t)` then the `fread` will fail and the loop will (effectively) end. `shader_load_from_disk` will also quietly fail if the read hash is invalid, in the case that the shader list is corrupted.

2022-03-19 18:19 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +    if (!shader_file) {
I can print a warning message ~and add a flag to ensure it's only printed once~. On second thought, I don't think a flag is necessary at this point, as the only possible failures have to do with writing the file.

2022-03-19 18:19 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +    written = fwrite(snode->program, snode->program_size, 1, shader_file);
Good catch. I'll write the size and validate the program on load to mitigate this.

2022-03-19 18:19 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +cleanup:
Will fix

2022-03-19 18:19 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +static void shader_cache_to_disk(ShaderLruNode *snode)
Theoretically it should be slower (LRU is backed by `QTAILQ`), but I didn't notice a performance impact on my system. However, it could just be that my system is fast and I don't have enough shaders in the cache to notice the difference.

2022-03-19 18:19 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +    /* program_size might be zero on some systems, if no binary formats are supported */
If `g_malloc` itself has failed then I would imagine things have already blown up, but I can make this check explicit.

2022-03-19 18:19 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +    snprintf(name, 20, "%llu", (unsigned long long) snode->node.hash);
Will fix

2022-03-19 18:19 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +    fwrite(&node->hash, sizeof(uint64_t), 1, lru_list_file);
What would you suggest the failure behavior be? I can print a log message but that may be noisy if subsequent writes also fail. I can't think of a way to recover otherwise from this point.

2022-03-19 18:19 UTC, antangelo commented on hw/xbox/nv2a/shaders.c
> +GLenum get_gl_primitive_mode(enum ShaderPolygonMode polygon_mode, enum ShaderPrimitiveMode primitive_mode)
Yes it's intentional, I need it when I create the `ShaderBinding` when loading from disk (and likewise for updating the constant locations).

2022-03-19 18:19 UTC, antangelo commented on hw/xbox/nv2a/shaders.c
> +        assert(false);
Will fix

2022-03-19 18:19 UTC, antangelo commented on ui/xemu-settings.c
> +	char *base = xemu_settings_detect_portable_mode()
Good idea, will fix

2022-03-19 18:19 UTC, antangelo commented on ui/xemu-settings.c
> +	char *path = g_malloc(strlen(base) + 1);
Will fix

2022-03-19 18:19 UTC, antangelo commented on ui/xemu-settings.c
>  const char *xemu_settings_get_path(void)
Will fix

2022-03-19 18:52 UTC, abaire commented on hw/xbox/nv2a/pgraph.c
> +    FILE *lru_list = qemu_fopen(shader_lru_path, "wb");
sg, having to regenerate a part of the cache seems no worse than having to regenerate the whole thing (which would be the case if we did a write-then-move and had it fail) so your approach seems better.

2022-03-19 18:52 UTC, abaire commented on hw/xbox/nv2a/pgraph.c
> +    if (glGetError() != GL_NO_ERROR) {
Making sure I understand the flow: the only way we'd anticipate hitting those would be if the shader loaded from disk has become invalid (either due to it being corrupted or the driver being updated). I think if you switch to doing explicit validation on the reload case it should no longer be possible for this to be hit?

If that's the case, then should we just assert instead of handling it silently-but-gracefully (and potentially hiding some failure mode)?

2022-03-19 18:52 UTC, abaire commented on hw/xbox/nv2a/pgraph.c
> +    fseek(lru_shaders_list, 0, SEEK_END);
Yeah, I don't think it's necessary to change, just something to note in case we hear about weird behavior on some esoteric platform in the future.

2022-03-19 18:52 UTC, abaire commented on hw/xbox/nv2a/pgraph.c
> +    for (size_t read = 0; read < shader_list_size; read += sizeof(uint64_t)) {
sg

2022-03-19 18:52 UTC, abaire commented on hw/xbox/nv2a/pgraph.c
> +    if (!shader_file) {
I'd say we should probably try to catch the case where shader bin formats aren't supported before even bothering to create the file, no?

My assumption is that once we're in this path we'd really expect to be able to write to the filesystem without any error, and failure to do basic writes would either mean there's some misconfiguration (e.g., read-only target) or some very unexpected low level error, both of which seem like they'd be good to know when debugging.

2022-03-19 18:52 UTC, abaire commented on hw/xbox/nv2a/pgraph.c
> +    written = fwrite(snode->program, snode->program_size, 1, shader_file);
Devil's advocate against my original suggestion - if you're going to validate the shaders on load, maybe we don't need to also save the size? I guess it'd let you bomb out early if the file is truncated, but presumably that'd be a rare case and if we're going to do full validation anyway I'm dubious that it'd save much time in practice.

2022-03-19 18:52 UTC, abaire commented on hw/xbox/nv2a/pgraph.c
> +    fwrite(&node->hash, sizeof(uint64_t), 1, lru_list_file);
I don't think it'd be unreasonable to log it, even if it's spammy, since it should essentially never happen in typical scenarios (I guess an out of HDD space case is the most likely culprit). If log spam is the biggest concern I think we could have opaque be a struct that has the `FILE *` and a boolean and just && the bool w/ the result, then log failure in `pgraph_cache_shaders_to_disk`.

That said, since it seems likely that opening the file would fail if the issue is an unwritable target (which strikes me as the most likely fail scenario), I guess it's also reasonable to go without a check here.

2022-03-19 18:56 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +    written = fwrite(snode->program, snode->program_size, 1, shader_file);
Writing the size removes the need for the `fseek` to file end, so it has other benefits that make it an attractive solution. Perhaps we don't need to validate the shader after loading it in memory, but I think it might be good practice to do so anyway.

2022-03-19 18:59 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +    if (!shader_file) {
My bad on this one, the case where shader bin formats are unsupported is detected beforehand, before this function is called. I'll add a print to stderr (which shouldn't have a performance impact since this is running in its own thread).

2022-03-19 19:03 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +    if (glGetError() != GL_NO_ERROR) {
That's correct. This path is happening on load, and I don't know if there's another way to check if the binary format is supported beforehand (or if it's worth doing, since the GL implementation will do it here as well).

2022-03-19 19:04 UTC, antangelo commented on hw/xbox/nv2a/shaders.c
> +    /* Create an option geometry shader and find primitive type */
Missed this last time, but will fix

2022-03-19 19:10 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +    fwrite(&node->hash, sizeof(uint64_t), 1, lru_list_file);
Since it's unlikely that the write will fail if open didn't fail, I'll add a log there for good measure. I'll also add a log if open failed, since I missed that initially.

2022-03-19 20:14 UTC, antangelo commented
Pushed some changes to reflect the review comments, but I have only tested them on Linux so far.

2022-03-19 20:57 UTC, mborgerson commented on hw/xbox/nv2a/pgraph.c
> +    const size_t shader_cache_size = 50*1024;
> I tested a game that compiled shaders every time the camera was moved, so I don't think this value is unreasonable
@antangelo which game was this?

2022-03-19 23:10 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +    const size_t shader_cache_size = 50*1024;
Battle for Bikini Bottom (5451001a). It's level dependent, but I haven't looked into what part of the shader state is changing so frequently.


https://user-images.githubusercontent.com/25046221/159141456-112253e4-6d62-44e2-b60c-cf2e23542890.mp4

2022-05-09 01:53 UTC, mborgerson requested changes
Thanks for the patch! Sorry about the review delay. Left some change requests

Also this needs a rebase but there are some conflicts. Can you please fix them up

2022-05-09 01:53 UTC, mborgerson commented on hw/xbox/nv2a/shaders.c
> +
nit: blank line

2022-05-09 01:53 UTC, mborgerson commented on ui/xemu-os-utils-windows.c
> +	BOOL dirResult = CreateDirectoryA(path, 0);
Should use unicode/wide version and convert `path` from utf-8 to utf-16

2022-05-09 01:53 UTC, mborgerson commented on hw/xbox/nv2a/pgraph.c
> +    const size_t shader_cache_size = 5;
5 is pretty low. Left over from debug?

2022-05-09 01:53 UTC, mborgerson commented on hw/xbox/nv2a/pgraph.c
> +    GLenum program_binary_format;
Let's also add a couple extra fields to avoid bugs:
* Let's add a check that strictly enforces we only load shaders generated by the exact same build of xemu
* We can also add a check for GL vendor/driver, which can change if someone is using a system with hybrid graphics for instance. If the current vendor doesn't match the vendor of the loaded shader we can skip uploading + validating the shader for it to just eventually fail.

2022-05-09 01:53 UTC, mborgerson commented on hw/xbox/nv2a/pgraph.c
> +    if(snode->binding) {
Let's do this check earlier, before opening/reading the shader program file, etc

2022-05-09 01:53 UTC, mborgerson commented on hw/xbox/nv2a/pgraph.c
> +    rcu_register_thread();
This thread doesn't use rcu so we can drop the registration

2022-05-09 01:53 UTC, mborgerson commented on hw/xbox/nv2a/pgraph.c
> +    rcu_register_thread();
This thread isn't using rcu, so we can drop this registration

2022-05-09 01:53 UTC, mborgerson commented on hw/xbox/nv2a/pgraph.c
> +    qemu_thread_create(&pg->shader_disk_thread, "pgraph.shader_cache", shader_reload_lru_from_disk, pg, QEMU_THREAD_JOINABLE);
Let's add a config item that controls whether or not we cache shaders. I added a stub item in config_spec.yml for this

2022-05-09 01:53 UTC, mborgerson commented on hw/xbox/nv2a/pgraph.c
> +    snprintf(shader_path, shader_path_len, "%s/shaders/%llu", cfg_dir, (unsigned long long) hash);
* We simplify the `strlen`+`malloc`+`sprintf` with `g_strdup_printf`
* Let's change the filename from decimal to hex and pad it to 16 digits (eg `"%016"PRIx64`)
* Let's bin the shaders into subdirectories based on some number of hash bits

2022-05-09 01:53 UTC, mborgerson commented on hw/xbox/nv2a/pgraph.c
> +    unlink(path);
* `unlink` (and other references here to it) should be using `qemu_unlink`
* `qemu_unlink` should be updated to use `_wunlink` on Windows, and convert the utf-8 path to utf-16 accordingly

2022-05-13 13:43 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +    const size_t shader_cache_size = 5;
My bad, this is left over from testing. As an aside, do you think the original `50 * 1024` is adequate, or should that number be increased/decreased in your opinion?

2022-05-16 00:45 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +    if(snode->binding) {
The earliest this can be done is after the state is read from disk (as the state struct is necessary to lookup the LRU node), at which point the only remaining item to be read is the shader program. If I did put a check for this there, we'd still need to check after the shader program is loaded from disk (the lock would be released before continuing to load from disk, and the shader might be regenerated between then and acquiring the lock again). I'm not sure if there's much utility in doing that, especially given that this runs once at startup and then never again.

2022-05-16 18:09 UTC, antangelo commented on hw/xbox/nv2a/shaders.c
> +
Fixed

2022-05-16 18:09 UTC, antangelo commented on ui/xemu-os-utils-windows.c
> +	BOOL dirResult = CreateDirectoryA(path, 0);
Done

2022-05-16 18:10 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +    GLenum program_binary_format;
Done, using xemu version string and GL vendor

2022-05-16 18:10 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +    rcu_register_thread();
Done

2022-05-16 18:10 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +    rcu_register_thread();
Done

2022-05-16 18:10 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +    qemu_thread_create(&pg->shader_disk_thread, "pgraph.shader_cache", shader_reload_lru_from_disk, pg, QEMU_THREAD_JOINABLE);
Done

2022-05-16 18:11 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +    snprintf(shader_path, shader_path_len, "%s/shaders/%llu", cfg_dir, (unsigned long long) hash);
Done, using first 16 bits for the bin and remaining 48 bits for the filename.

2022-05-16 18:11 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +    unlink(path);
Done

2022-05-17 01:26 UTC, mborgerson commented on hw/xbox/nv2a/pgraph.c
> +static void shader_cache_entry_init(Lru *lru, LruNode *node, void *state)
Let's move all this new shader code to shaders.c

2022-05-17 01:26 UTC, mborgerson commented on hw/xbox/nv2a/pgraph.c
> +    if(snode->binding) {
Hash collision should be rare but in the event it does happen, it would conflict on disk anyway. We can just check the cache and see if we already have a generated shader before checking the filesystem. It can be that the shader is generated very early in startup for instance while we are loading a potentially large cache of shaders, so we can move the check up without cost and skip loading if its already generated

2022-05-17 02:06 UTC, mborgerson commented on hw/xbox/nv2a/pgraph.c
> +    uint64_t xemu_cache_version_len;
Can we refactor this read size / read data pattern to make this function smaller

2022-05-17 02:06 UTC, mborgerson commented on hw/xbox/nv2a/nv2a_int.h
> +    QemuEvent shader_cache_complete;
The event names are kind of ambiguous about what they signify. I think `shader_cache_disk_writeback_complete` or something like that might be more clear, for instance

2022-05-17 02:06 UTC, mborgerson commented on hw/xbox/nv2a/pgraph.c
> +        fclose(shader_file);
Let's refactor this 8x repeated pattern

2022-05-17 02:14 UTC, mborgerson commented on ui/xemu-os-utils-linux.c
> +int xemu_mkdir(const char *path)
The preferred place for these kinds of functions is osdep.h with other functions like qemu_{open, close, ...}

2022-05-17 02:20 UTC, mborgerson commented on ui/xemu-settings.cc
> +    if (base_path != NULL) {
Let's move `base_path` scope into this function

2022-06-04 10:41 UTC, Adamillo commented
@antangelo what's the state of this PR?

2022-06-04 17:42 UTC, antangelo commented
> @antangelo what's the state of this PR?

Needs a few changes, I'll probably have time to get back to it in the next week or so.

2022-06-19 04:59 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +static void shader_cache_entry_init(Lru *lru, LruNode *node, void *state)
Done

2022-06-19 04:59 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +    if(snode->binding) {
Done, I added an early check using the hash only.

2022-06-19 05:01 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +    uint64_t xemu_cache_version_len;
Done, added a similar macro to writes

2022-06-19 05:01 UTC, antangelo commented on hw/xbox/nv2a/nv2a_int.h
> +    QemuEvent shader_cache_complete;
Done

2022-06-19 05:01 UTC, antangelo commented on hw/xbox/nv2a/pgraph.c
> +        fclose(shader_file);
Done, moved into macro

2022-06-19 05:01 UTC, antangelo commented on ui/xemu-os-utils-linux.c
> +int xemu_mkdir(const char *path)
Done

2022-06-19 05:01 UTC, antangelo commented on ui/xemu-settings.cc
> +    if (base_path != NULL) {
Done

2022-06-21 07:45 UTC, mborgerson commented on hw/xbox/nv2a/shaders.c
> +        fprintf(stderr, "nv2a: Failed to write shader list entry %llu to disk\n",
Hashes are identified by 64b hex number so let's printf `%lx` here instead

2022-06-21 07:45 UTC, mborgerson commented on hw/xbox/nv2a/shaders.c
> +    qemu_mkdir(shader_bin_dir);
I think we should not *create* directories in this function, rather only create the directory when writing the shaders out to disk if it doesn't exist yet

2022-06-21 07:45 UTC, mborgerson commented on hw/xbox/nv2a/shaders.c
> +        g_free(snode->program);
We should set `snode->program = NULL;` here?

2022-06-21 07:45 UTC, mborgerson commented on hw/xbox/nv2a/shaders.c
> +    snprintf(name, 27, "scache-%llu", (unsigned long long) snode->node.hash);
* Possible truncation (name should be 28 to fit maximal hash value and null byte)
* With hex representation it would be 24

2022-06-21 07:45 UTC, mborgerson commented on hw/xbox/nv2a/shaders.c
> +    FILE *shader_file = qemu_fopen(shader_path, "rb");
Another latency optimization for this system would be combining all of the shaders into one big file to reduce startup disk I/O overhead. Could wait for a follow-up, just noting it here for future iteration.

2022-06-21 07:45 UTC, mborgerson commented on hw/xbox/nv2a/shaders.c
> +bool shader_load_from_memory(ShaderLruNode *snode)
I took a brief look at the performance impact of loading and validating shaders at runtime in the way this implementation does by instrumenting this function to print out some experimental measurements. Playing around in Halo 2 with a 'warm' cache, the per-frame latency added here if the shaders for that frame are pre-loaded from disk but not yet created in GL are: min=284us median=1242us, max=29797us. Even with the savings of having the shader program 'binary' in memory, it looks like loading and validating can still add some significant latency.

I augmented the patch to create all the shader programs up front and eliminate this runtime cost. About 13ms to load ~615 shaders from disk, and 333ms to load them into GL state. I'm not certain what the impact will be after long-term practical user play, but scaling this figure out to the current shader cache size of `50*1024` suggests a possible startup cost of something like `(346/615)*(50*1024)=28805ms`. Intermittent frame latency is not great, but nearly 30s of startup latency is also not a good user experience. The cache size could be reduced to limit the up-front loading cost, but even at a tenth of the size, 2.8 seconds would be noticeable and annoying startup delay.

A compromise between the full-lazy and full-upfront approaches would be loading these shaders at startup, but in a separate context; that way we would not block startup, and be able to reduce some latency compared to the full-lazy approach.

Anyway, I think the approach in this patch is good as it is, and we can defer this proposed improvement to a follow-up.

2022-06-21 07:45 UTC, mborgerson commented on hw/xbox/nv2a/shaders.c
> +    const size_t shader_cache_size = 50*1024;
I don't really know what the right number would be for this. We may want to make this configurable.

2022-06-21 07:57 UTC, mborgerson commented on hw/xbox/nv2a/shaders.c
> +    *gl_primitive_mode = get_gl_primitive_mode(polygon_mode, primitive_mode);
Let's move this function up so we only set `gl_primitive_mode` the one time

2022-07-01 02:11 UTC, antangelo commented on hw/xbox/nv2a/shaders.c
> +        fprintf(stderr, "nv2a: Failed to write shader list entry %llu to disk\n",
Done

2022-07-01 02:11 UTC, antangelo commented on hw/xbox/nv2a/shaders.c
> +    qemu_mkdir(shader_bin_dir);
Done, moved to before the shader file is opened.

2022-07-01 02:12 UTC, antangelo commented on hw/xbox/nv2a/shaders.c
> +        g_free(snode->program);
Yes, thanks for the catch. I believe this can only be an issue in the edge case below where the platform doesn't support shader binaries (otherwise we set it almost immediately afterwards anyway).

2022-07-01 02:13 UTC, antangelo commented on hw/xbox/nv2a/shaders.c
> +    snprintf(name, 27, "scache-%llu", (unsigned long long) snode->node.hash);
Done, switched to hex and adjusted size accordingly

2022-07-01 02:18 UTC, antangelo commented on hw/xbox/nv2a/shaders.c
> +    FILE *shader_file = qemu_fopen(shader_path, "rb");
Unless I'm mistaken, this would necessitate jumping through the file to determine the individual shader offsets (as the binary sizes are not constant), before the loading work can be parallelized. Would be interesting to see if this diminishes the IO performance benefits

2022-07-01 02:21 UTC, antangelo commented on hw/xbox/nv2a/shaders.c
> +    const size_t shader_cache_size = 50*1024;
Gotcha, I've added a fixme comment above to indicate this

2022-07-01 02:21 UTC, antangelo commented on hw/xbox/nv2a/shaders.c
> +    *gl_primitive_mode = get_gl_primitive_mode(polygon_mode, primitive_mode);
Done

2022-07-14 10:21 UTC, Adamillo commented
@mborgerson are there any other changes required in order for this PR to get merged?

2022-09-08 07:42 UTC, Spidy123222 commented
From testing it seems I have some issues with burnout 3 with this PR. 

before restart you can see it has a black blob on the streets on the texturing.
https://cdn.discordapp.com/attachments/680488810429153315/1017332510566404136/Screenshot_300.png

After a xemu restart it is much more clearly green on the texture ahead.
https://cdn.discordapp.com/attachments/680488810429153315/1017332528065019914/Screenshot_301.png

Master branch has not had this issue as i have tested multiple versions of master branch and here is example versions 0.7.67, 0.7.66, 0.7.64, 0.6.2-90.
https://cdn.discordapp.com/attachments/680488810429153315/1017332560491196456/Screenshot_302.png

Hope this info is helpful to you

2022-09-09 21:28 UTC, mborgerson commented
@Spidy123222 

> From testing it seems I have some issues with burnout 3 with this PR.

I recall these issues being fixed on master branch previously. I've rebased this PR now, can you test again and confirm whether the issues are still present or resolved?

2022-09-10 07:46 UTC, Spidy123222 commented
> @Spidy123222
> 
> > From testing it seems I have some issues with burnout 3 with this PR.
> 
> I recall these issues being fixed on master branch previously. I've rebased this PR now, can you test again and confirm whether the issues are still present or resolved?

I don’t see any problems after rebasing. It helps some performance on some games and load times.

2022-09-10 19:37 UTC, mborgerson commented
Nice job!

2022-09-10 19:52 UTC, merged