nv2a: Match HW behavior when setting window clip
xemu-project/xemu pull request #908
Opened 2022-05-09 04:50 UTC by abaire

Fixes #907 

[Test](https://github.com/abaire/nxdk_pgraph_tests/blob/main/src/tests/window_clip_tests.cpp)
[HW results](https://github.com/abaire/nxdk_pgraph_tests_golden_results/wiki/Results-Window_clip)

2022-05-09 14:14 UTC, abaire commented
Found an additional bug in xemu wrt. dealing with clip regions larger than the surface size (there's a signed/unsigned mismatch). Pulling that fix into this PR so the improved tests pass.

2022-05-09 21:53 UTC, abaire commented
Looks like that bug is in the final display only (the surfaces emulating the guest are fine, the error is introduced in the last display blit). Will file a second bug and fix for that.

2022-05-10 08:31 UTC, mborgerson requested changes
Please remove the updated submodule and I'll merge

2022-05-10 08:31 UTC, mborgerson commented on hw/xbox/nv2a/pgraph.c
> +        pg->regs[NV_PGRAPH_WINDOWCLIPX0 + slot * 4] = parameter;
Nice discovery! I confirmed this with your test

2022-05-10 13:42 UTC, abaire commented
> Please remove the updated submodule and I'll merge

Oops, fixed. My script to auto rebase my PR branches apparently doesn't account for submodule update properly.

2022-05-10 20:15 UTC, merged