nv2a: Set vram size before VGA init
xemu-project/xemu pull request #95
Opened 2020-12-03 12:49 UTC by haxar

This PR supports loading xbox-linux with 128 MiB of VRAM when Cromwell sets the framebuffer location to the end of VRAM, so it is not stuck at the Linux loading screen.

It prevents `vga_draw_graphic()` from setting `force_shadow` with a previously hardcoded VRAM size of 64 MiB, allowing `simplefb` to display.

After:
![Screenshot at 2020-12-03 03-53-20](https://user-images.githubusercontent.com/50159600/101019717-363c1700-3522-11eb-882f-1e5c6f40b39f.png)
Before:
![Screenshot at 2020-12-03 04-34-45](https://user-images.githubusercontent.com/50159600/101019734-3c31f800-3522-11eb-92da-164e8f633b79.png)

2020-12-04 00:35 UTC, GXTX commented on hw/xbox/nv2a/nv2a.c
> +    vga->vram_size_mb = (d->vram_size_mb == 128) ? 128 : 64;
Why not?

```
vga->vram_size_mb = d->vram_size_mb;
```

2020-12-04 01:13 UTC, haxar commented on hw/xbox/nv2a/nv2a.c
> +    vga->vram_size_mb = (d->vram_size_mb == 128) ? 128 : 64;
I have no objection to this.

2020-12-04 22:17 UTC, mborgerson requested changes

2020-12-04 22:17 UTC, mborgerson commented on hw/xbox/xbox_pci.c
> +        /* FIXME: xbox-linux queries in this range, so just return an unused irq? for now */
Huh? What device is it trying to bring up here?

2020-12-04 22:17 UTC, mborgerson commented on hw/xbox/nv2a/nv2a.c
> +static Property nv2a_properties[] = {
Let's avoid adding this new property and instead refactor the vga init inside `realize` into a new function that gets called after memory init and then you can `memory_region_size(d->vram)`

2020-12-04 23:50 UTC, haxar commented on hw/xbox/xbox_pci.c
> +        /* FIXME: xbox-linux queries in this range, so just return an unused irq? for now */
I assume it's Linux enumerating all the PCI devices, but not able to confirm since `simplefb` is not initialized at that point & can't see dmesg (black screen).

2020-12-04 23:53 UTC, haxar commented on hw/xbox/nv2a/nv2a.c
> +static Property nv2a_properties[] = {
Good call on the refactor.

2020-12-05 13:41 UTC, haxar commented on hw/xbox/xbox_pci.c
> +        /* FIXME: xbox-linux queries in this range, so just return an unused irq? for now */
`xbox-pci`, `xbox-lpc` & `xbox-smbus` don't have mappable IRQs, which may cause us to use the default case & hit this assert.

See `xbox_pci: Remove assert for pci_update_irq_disabled()` for more info.

2020-12-06 10:13 UTC, haxar commented on hw/xbox/xbox_pci.c
> +        /* FIXME: xbox-linux queries in this range, so just return an unused irq? for now */
There's also this previous convo regarding the above comment to give more context:

> https://discord.com/channels/428359196719972353/616286065355128832/619425788776808448
JayFoxRox 09/05/2019
I never understood the XQEMU / Xbox PCI IRQ remapping stuff btw; and the comments suggest it's hardcoded based on trial and error, too :stuck_out_tongue:
it's also one of those things that's hard to test on hardware [to me]
https://github.com/xqemu/xqemu/blob/dd1248a563af6cfb024a68d21250069b5c41e25e/hw/xbox/xbox_pci.c#L122 here's that comment for the XQEMU code - also the function above probably would have deserved some explanations

2020-12-08 02:29 UTC, mborgerson commented on hw/xbox/nv2a/nv2a_int.h
> +#include "qemu/units.h"
Is this necessary

2020-12-09 14:47 UTC, haxar commented on hw/xbox/nv2a/nv2a_int.h
> +#include "qemu/units.h"
This provides `MiB` & is used for `memory_region_size(d->vram) / MiB`.

2020-12-10 10:04 UTC, haxar commented on hw/xbox/xbox_pci.c
> +        /* FIXME: xbox-linux queries in this range, so just return an unused irq? for now */
The above devices don't have interrupts to set. My latest force-push should be a better solution.

2020-12-11 04:06 UTC, haxar commented on hw/xbox/xbox_pci.c
> +        return XBOX_NUM_INT_IRQS + XBOX_NUM_PIRQS;
OK, this won't work since this can cause an out of bounds access with `bus->irq_count[irq_num]` in `pci_change_irq_level()` when the array is this large (`bus->nirq == XBOX_NUM_INT_IRQS + XBOX_NUM_PIRQS`). This function (`xbox_lpc_map_irq()`) is returning an index to a nibble at the below mentioned LPC PCI configuration register.

Just PCI slot 0 & 1 need to be mapped somewhere & they have to be a device on the internal bus. The LPC PCI configuration register at `lpc->dev.config + XBOX_LPC_INT_IRQ_ROUT` provides the actual IRQ mappings & only 2 nibbles are actually `0`, which may map respectively & don't have to set an interrupt when `pic_irq == 0`.

2021-01-25 01:13 UTC, mborgerson commented on hw/xbox/xbox_pci.c
> +    case 0: return 5; /* hostbridge, no IRQ */
Is this a guess based on unassigned routes, or did you verify that these are the correct routes for these particular slots?

Either way it should be okay

2021-01-25 01:13 UTC, mborgerson commented on hw/xbox/xbox_pci.c
> +     * 0x0e065491 @ XBOX_LPC_INT_IRQ_ROUT
Confirmed on my box as well

2021-01-25 01:13 UTC, mborgerson commented on hw/xbox/xbox_pci.c
> +     * 0x00031000 @ XBOX_LPC_PIRQ_ROUT
Confirmed on my box as well

2021-01-27 09:42 UTC, haxar commented on hw/xbox/xbox_pci.c
> +    case 0: return 5; /* hostbridge, no IRQ */
This is a guess & not able to verify if this is correct. These slots should not have a mappable interrupt & should safely not assert one.

2021-11-12 02:15 UTC, GXTX commented
Just pinging to bring attention to the maintainer that this is still open.

2021-12-06 17:53 UTC, MasonT8198 commented
> Just pinging to bring attention to the maintainer that this is still open.

@mborgerson are there any outstanding issues with this being merged

2022-01-07 23:19 UTC, merged

2022-01-07 23:19 UTC, mborgerson commented
Thanks! Sorry about the long merge time